[package]
name = "fo-indexer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
walkdir = "2"
notify = "6"

[target.'cfg(windows)'.dependencies]
ntfs = "0.4"
windows = { version = "0.58", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3"
