[package]
name = "fo-search"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
fo-indexer.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }

[dev-dependencies]
fo-dedup.workspace = true
fo-hasher.workspace = true
tempfile = "3"
