[package]
name = "fo-dedup"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
fo-indexer.workspace = true
fo-hasher.workspace = true
rayon = "1"
image = "0.25"
image_hasher = "3"

[dev-dependencies]
tempfile = "3"
